title: "Report"
project:
  type: website
  output-dir: docs
  render:
    - eda.ipynb
    - dvc-compare-models.ipynb
  resources: 
    - "report/snake.html"
  
format:
  html:
    code-fold: true
    anchor-sections: true
    include-in-header:
      - text: <a href="report/snake.html">Snakemake report</a>
      - text: <a href="dvc-compare-models.html">DVC compare models</a>
jupyter: python3
execute:
  freeze: auto
  echo: false