stages:
  split_data:
    cmd: python ./sms_split_data.py
    deps:
    - ./sms_split_data.py
    - ${data.raw_data_path}
    outs:
    - ${data.split_dir}

  preprocess:
    cmd: python ./sms_preprocess.py
    deps:
      - ./sms_preprocess.py
      - ${data.split_dir}
    outs:
      - ${data.vectorized_dir}

  train:
    cmd: python ./sms_cls.py
    deps:
      - ./sms_cls.py
      - ${data.vectorized_dir}
    plots:
      - ${data.metrics_dir}/val/conf_matrix.csv:
          template: confusion
          x: predicted
          y: actual
      - ${data.metrics_dir}/test/conf_matrix.csv:
          template: confusion
          x: predicted
          y: actual
      - ${data.metrics_dir}/train/conf_matrix.csv:
          template: confusion
          x: predicted
          y: actual
    metrics:
      - ${data.metrics_dir}/val/roc_auc.json
      - ${data.metrics_dir}/test/roc_auc.json
      - ${data.metrics_dir}/train/roc_auc.json
