split_info:
  seed: 823787234
  train_size: 0.7
  val_size: 0.4
data:
  raw_data_path: data/dvc/raw/sentiment+labelled+sentences.zip
  fsspec_path: zip::file://data/dvc/raw/sentiment+labelled+sentences.zip
  split_dir: data/dvc/data
  vectorized_dir: data/dvc/vectorized
  metrics_dir: data/dvc/metrics
  class_mapping:
    positive: 1
    negative: 0
vectorizer:
  _target_: ods_mlops.sms_cls.vectorizer.Vectorizer
  stat_type: tfidf
model:
  inner_estimator:
    _target_: sklearn.linear_model.LogisticRegression
    random_state: 123324
    C: 100
    class_weight: balanced
  cls:
    _target_: ods_mlops.sms_cls.model.SkCls
    vectorizer:
      _target_: ods_mlops.sms_cls.vectorizer.Vectorizer
      stat_type: tfidf
    estimator:
      _target_: sklearn.linear_model.LogisticRegression
      random_state: 123324
      C: 100
      class_weight: balanced
exp_logger:
  _target_: ods_mlops.exp_loggers.mlflow.MLflowLogger
  exp_name: SMS classifications
  tracking_url: http://127.0.0.1:8080
