apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: docker.io/library/ods-mlops-web:latest
          imagePullPolicy: IfNotPresent
          command: ["uvicorn"] 
          args: 
            - ods_mlops.web.app:app 
            - --host
            - '0.0.0.0' 
            - --port 
            - '8080'
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128M"
            limits:
              cpu: 1
              memory: "500M"
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: ml.ods.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-server-service
                port:
                  number: 80
